---
- name: deploy MySQL and configure the databases
  hosts: dbservers
  user: vagrant
  sudo: yes

  roles:
    - common
    - db

- name: configure and deploy the webservers and application code
  hosts: webservers
  user: vagrant
  sudo: yes

  roles:
    - common
    - web

- name: configure and deploy the webservers and application code
  hosts: loadbalancer
  user: vagrant
  sudo: yes

  roles:
    - common
    - lb

