# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "lb" do |lb|
    lb.vm.box = "hashicorp/precise32"
    lb.vm.hostname = "lb"
    lb.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "hashicorp/precise32"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "hashicorp/precise32"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/precise32"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.13"
  end
end
